name: CI

on:
  push:
    branches:
      - 10.2HD
  pull_request:
    branches:
      - 10.2HD

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint .

  sonar:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"

      - name: Run SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Store your SonarQube token in GitHub Secrets
        run: |
          sonar-scanner \
            -Dsonar.organization=sandali95
            -Dsonar.projectKey=sandali95_chapter10
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
